// <auto-generated />
using System;
using Appointments.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appointments.Infrastructure.Migrations
{
    [DbContext(typeof(AppointmentsContext))]
    [Migration("20250925155601_Add_ExternalLocationId")]
    partial class Add_ExternalLocationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointments.Domain.Entities.AppointmentConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ExternalLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("AppointmentConfigurations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AppointmentConfigurationsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Attende", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentConfigurationId");

                    b.ToTable("Attendes", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AttendesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentConfigurationId")
                        .IsUnique()
                        .HasFilter("[AppointmentConfigurationId] IS NOT NULL");

                    b.HasIndex("RecurrenceId");

                    b.ToTable("Events", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("EventsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Recurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FirstStartOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastStartOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentConfigurationId")
                        .IsUnique();

                    b.ToTable("Recurrences", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("RecurrencesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ExternalServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentConfigurationId");

                    b.ToTable("Services", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServicesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Attende", b =>
                {
                    b.HasOne("Appointments.Domain.Entities.AppointmentConfiguration", "Configuration")
                        .WithMany("Attendes")
                        .HasForeignKey("AppointmentConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Event", b =>
                {
                    b.HasOne("Appointments.Domain.Entities.AppointmentConfiguration", "Configuration")
                        .WithOne("Event")
                        .HasForeignKey("Appointments.Domain.Entities.Event", "AppointmentConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Appointments.Domain.Entities.Recurrence", "Recurrence")
                        .WithMany("Events")
                        .HasForeignKey("RecurrenceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Configuration");

                    b.Navigation("Recurrence");
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Recurrence", b =>
                {
                    b.HasOne("Appointments.Domain.Entities.AppointmentConfiguration", "Configuration")
                        .WithOne("Recurrence")
                        .HasForeignKey("Appointments.Domain.Entities.Recurrence", "AppointmentConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Service", b =>
                {
                    b.HasOne("Appointments.Domain.Entities.AppointmentConfiguration", "Configuration")
                        .WithMany("Services")
                        .HasForeignKey("AppointmentConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Appointments.Domain.Entities.AppointmentConfiguration", b =>
                {
                    b.Navigation("Attendes");

                    b.Navigation("Event");

                    b.Navigation("Recurrence");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Appointments.Domain.Entities.Recurrence", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
