// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Setups.Infrastructure.Context;

#nullable disable

namespace Setups.Infrastructure.Migrations
{
    [DbContext(typeof(SetupsContext))]
    [Migration("20250920210241_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Setups.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AddressesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Buildings", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BuildingsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("CitiesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ClientTierId");

                    b.ToTable("Clients", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ClientsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ClientTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("ClientTiers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ClientTiersHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("CountriesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Floor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LocationTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Room")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocationTierId");

                    b.ToTable("Locations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("LocationsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.LocationTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("LocationTiers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("LocationTiersHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProviderTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ProviderTierId");

                    b.ToTable("Providers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProvidersHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ProviderTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("ProviderTiers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProviderTiersHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ServiceTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTierId");

                    b.ToTable("Services", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServicesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceCommission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommissionPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceProvisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProvisionId");

                    b.ToTable("ServiceCommissions", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServiceCommissionsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceProvisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProvisionId");

                    b.ToTable("ServiceDiscounts", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServiceDiscountsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServicePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximumUnits")
                        .HasColumnType("int");

                    b.Property<int>("MinimumUnits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ServiceProvisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProvisionId");

                    b.ToTable("ServicePrices", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServicePricesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceProvision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EndOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LocationTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProviderTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ClientTierId");

                    b.HasIndex("LocationTierId");

                    b.HasIndex("ProviderTierId");

                    b.HasIndex("ServiceTierId");

                    b.ToTable("ServiceProvisions", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServiceProvisionsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("ServiceTiers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ServiceTiersHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Code")
                        .HasFilter("Deleted = 0");

                    b.ToTable("States", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("StatesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UnitsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Setups.Domain.Entities.Address", b =>
                {
                    b.HasOne("Setups.Domain.Entities.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Building", b =>
                {
                    b.HasOne("Setups.Domain.Entities.Address", "Address")
                        .WithMany("Buildings")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Setups.Domain.Entities.City", b =>
                {
                    b.HasOne("Setups.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Client", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ClientTier", "Tier")
                        .WithMany("Clients")
                        .HasForeignKey("ClientTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Location", b =>
                {
                    b.HasOne("Setups.Domain.Entities.Building", "Building")
                        .WithMany("Locations")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Setups.Domain.Entities.LocationTier", "Tier")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Provider", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ProviderTier", "Tier")
                        .WithMany("Providers")
                        .HasForeignKey("ProviderTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Service", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ServiceTier", "Tier")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceCommission", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ServiceProvision", "ServiceProvision")
                        .WithMany("Commissions")
                        .HasForeignKey("ServiceProvisionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceProvision");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceDiscount", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ServiceProvision", "ServiceProvision")
                        .WithMany("Discounts")
                        .HasForeignKey("ServiceProvisionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceProvision");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServicePrice", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ServiceProvision", "ServiceProvision")
                        .WithMany("Prices")
                        .HasForeignKey("ServiceProvisionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ServiceProvision");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceProvision", b =>
                {
                    b.HasOne("Setups.Domain.Entities.ClientTier", "ClientTier")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("ClientTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Setups.Domain.Entities.LocationTier", "LocationTier")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("LocationTierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Setups.Domain.Entities.ProviderTier", "ProviderTier")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("ProviderTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Setups.Domain.Entities.ServiceTier", "ServiceTier")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("ServiceTierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientTier");

                    b.Navigation("LocationTier");

                    b.Navigation("ProviderTier");

                    b.Navigation("ServiceTier");
                });

            modelBuilder.Entity("Setups.Domain.Entities.State", b =>
                {
                    b.HasOne("Setups.Domain.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Address", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Building", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Setups.Domain.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ClientTier", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Setups.Domain.Entities.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Setups.Domain.Entities.LocationTier", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ProviderTier", b =>
                {
                    b.Navigation("Providers");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceProvision", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Discounts");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Setups.Domain.Entities.ServiceTier", b =>
                {
                    b.Navigation("ServiceProvisions");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Setups.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
