// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payments.Infrastructure.DbContext;

#nullable disable

namespace Payments.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentsContext))]
    [Migration("20250911170945_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payments.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Bills", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BillsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsCount")
                        .HasColumnType("int");

                    b.Property<string>("UnitsName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BillItemsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillItemSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("BillItemId", "SourceType", "SourceId")
                        .IsUnique()
                        .HasFilter("Deleted = 0");

                    b.ToTable("BillItemSources", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BillItemSourcesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("BillId", "SourceType", "SourceId")
                        .IsUnique()
                        .HasFilter("Deleted = 0");

                    b.ToTable("BillSources", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BillSourcesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Payments.Domain.Entities.PaymentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountData")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("PaymentEntityId");

                    b.ToTable("PaymentAccounts", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PaymentAccountsHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Payments.Domain.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VersionEndFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionEndFrom");

                    b.Property<DateTime>("VersionStartFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("VersionStartFrom");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("Deleted = 0");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasFilter("Deleted = 0");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasFilter("Deleted = 0");

                    b.HasIndex("ClientId", "ProviderId", "CompanyId")
                        .HasFilter("Deleted = 0");

                    b.ToTable("PaymentEntities", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentEntity_ExternalId", "Deleted = 0 OR ((ClientId IS NOT NULL OR ProviderId IS NOT NULL OR CompanyId IS NOT NULL))");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PaymentEntitiesHistory");
                                ttb
                                    .HasPeriodStart("VersionStartFrom")
                                    .HasColumnName("VersionStartFrom");
                                ttb
                                    .HasPeriodEnd("VersionEndFrom")
                                    .HasColumnName("VersionEndFrom");
                            }));
                });

            modelBuilder.Entity("Payments.Domain.Entities.Bill", b =>
                {
                    b.HasOne("Payments.Domain.Entities.PaymentAccount", "Receiver")
                        .WithMany("ReceivedBills")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Payments.Domain.Entities.PaymentAccount", "Sender")
                        .WithMany("SentBills")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillItem", b =>
                {
                    b.HasOne("Payments.Domain.Entities.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillItemSource", b =>
                {
                    b.HasOne("Payments.Domain.Entities.BillItem", "BillItem")
                        .WithMany("BillItemSources")
                        .HasForeignKey("BillItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BillItem");
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillSource", b =>
                {
                    b.HasOne("Payments.Domain.Entities.Bill", "Bill")
                        .WithMany("BillSources")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Payments.Domain.Entities.PaymentAccount", b =>
                {
                    b.HasOne("Payments.Domain.Entities.PaymentEntity", "PaymentEntity")
                        .WithMany("PaymentAccounts")
                        .HasForeignKey("PaymentEntityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentEntity");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Bill", b =>
                {
                    b.Navigation("BillItems");

                    b.Navigation("BillSources");
                });

            modelBuilder.Entity("Payments.Domain.Entities.BillItem", b =>
                {
                    b.Navigation("BillItemSources");
                });

            modelBuilder.Entity("Payments.Domain.Entities.PaymentAccount", b =>
                {
                    b.Navigation("ReceivedBills");

                    b.Navigation("SentBills");
                });

            modelBuilder.Entity("Payments.Domain.Entities.PaymentEntity", b =>
                {
                    b.Navigation("PaymentAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
